// Generated by CoffeeScript 1.10.0
(function() {
  var config, too_big;

  config = require('config');


  /*
  Do a check to see if the image is too large to service the request.
  See config/default.yml for more information on the upsize_factor setting.
   */

  too_big = function(params, info) {
    return params.size.w > params.region.w * config.get('upsize_factor');
  };

  exports.too_big = too_big;

}).call(this);
