// Generated by CoffeeScript 1.10.0

/*
Simple file resolver!
This could be changed to find images split across directories based on the id
or look up the path to the image in a database. In this case we know all the
images are going to be JP2s.
 */

(function() {
  var base_path, config, log, nested_file_resolver, path, resolve_image_path, resolver_base_path, sanitize_id, simple_file_resolver;

  path = require('path');

  log = require('./index').log;

  config = require('config');

  resolver_base_path = config.get('resolver.base_path');

  sanitize_id = function(id) {
    id.replace(/\./g, '');
    return id;
  };

  base_path = resolver_base_path ? resolver_base_path : path.join(__dirname, "/../images/");

  simple_file_resolver = function(id, filename) {
    return path.join(base_path, filename);
  };

  nested_file_resolver = function(id, filename) {
    var first_n, nested_number;
    nested_number = config.get('resolver.nested_number');
    first_n = id.substring(0, nested_number);
    return path.join(base_path, first_n, filename);
  };

  resolve_image_path = function(id) {
    var clean_id, filename, image_path;
    clean_id = sanitize_id(id);
    filename = clean_id + ".jp2";
    image_path = config.get('resolver.type') === 'simple' ? (console.log('SIMPLE'), simple_file_resolver(clean_id, filename)) : config.get('resolver.type') === 'nested' ? nested_file_resolver(clean_id, filename) : void 0;
    console.log(image_path);
    return image_path;
  };

  exports.resolve_image_path = resolve_image_path;

}).call(this);
