// Generated by CoffeeScript 1.10.0
(function() {
  var config, path, server_info;

  path = require('path');

  config = require('config');

  server_info = function(req, id) {
    var full_server_info, info_id, scheme, server_info_id;
    scheme = req.connection.encrypted != null ? 'https' : 'http';
    info_id = path.join(req.headers.host, config.get('prefix'), id);
    server_info_id = scheme + "://" + info_id;
    full_server_info = {
      id: server_info_id,
      level: 1
    };
    return full_server_info;
  };

  module.exports = server_info;

}).call(this);
