// Generated by CoffeeScript 1.10.0
(function() {
  var slugify_path;

  slugify_path = function(url_or_path) {
    return url_or_path.replace('/', '').replace(/\//g, '--').replace(/,/g, '_');
  };

  module.exports = slugify_path;

}).call(this);
